import { Divide } from "phosphor-react";

export default function Badges() {
  return (
    <div>
      <div className="flex flex-wrap mt-3 gap-2">
        <img
          src="https://img.shields.io/badge/C%23-%23239120.svg?style=flat&amp;logo=csharp&amp;logoColor=white"
          alt="C#"
        ></img>
        <img
          src="https://img.shields.io/badge/CSS3-%231572B6.svg?style=flat&amp;logo=css3&amp;logoColor=white"
          alt="CSS3"
        ></img>
        <img
          src="https://img.shields.io/badge/HTML5-%23E34F26.svg?style=flat&amp;logo=html5&amp;logoColor=white"
          alt="HTML5"
        ></img>
        <img
          src="https://img.shields.io/badge/Javascript-%23323330.svg?style=flat&amp;logo=javascript&amp;logoColor=%23F7DF1E"
          alt="JavaScript"
        ></img>
        <img
          src="https://img.shields.io/badge/npm-%23CB3837.svg?style=flat&amp;logo=npm&amp;logoColor=white"
          alt="NPM"
        ></img>
        <img
          src="https://img.shields.io/badge/Markdown-%23000000.svg?style=flat&amp;logo=markdown&amp;logoColor=white"
          alt="Markdown"
        ></img>
        <img
          src="https://img.shields.io/badge/PowerShell-%235391FE.svg?style=flat&amp;logo=powershell&amp;logoColor=white"
          alt="PowerShell"
        ></img>
        <img
          src="https://img.shields.io/badge/Typescript-%23007ACC.svg?style=flat&amp;logo=typescript&amp;logoColor=white"
          alt="TypeScript"
        ></img>
        <img
          src="https://img.shields.io/badge/Azure-%230072C6.svg?style=flat&amp;logo=microsoftazure&amp;logoColor=white"
          alt="Azure"
        ></img>
        <img
          src="https://img.shields.io/badge/Firebase-%23039BE5.svg?style=flat&amp;logo=firebase"
          alt="Firebase"
        ></img>
        <img
          src="https://img.shields.io/badge/Netlify-%23000000.svg?style=flat&amp;logo=netlify&amp;logoColor=#00C7B7"
          alt="Netlify"
        ></img>
        <img
          src="https://img.shields.io/badge/Vercel-%23000000.svg?style=flat&amp;logo=vercel&amp;logoColor=white"
          alt="Vercel"
        ></img>
        <img
          src="https://img.shields.io/badge/.NET-5C2D91?style=flat&amp;logo=.net&amp;logoColor=white"
          alt=".Net"
        ></img>
        <img
          src="https://img.shields.io/badge/JWT-black?style=flat&amp;logo=JSON%20web%20tokens"
          alt="JWT"
        ></img>
        <img
          src="https://img.shields.io/badge/Bootstrap-%238511FA.svg?style=flat&amp;logo=bootstrap&amp;logoColor=white"
          alt="Bootstrap"
        ></img>
        <img
          src="https://img.shields.io/badge/Chakra-%234ED1C5.svg?style=flat&amp;logo=chakraui&amp;logoColor=white"
          alt="Chakra"
        ></img>

        <img
          src="https://img.shields.io/badge/jQuery-%230769AD.svg?style=flat&amp;logo=jquery&amp;logoColor=white"
          alt="jQuery"
        ></img>

        <img
          src="https://img.shields.io/badge/Next-black?style=flat&amp;logo=next.js&amp;logoColor=white"
          alt="NextJS"
        ></img>
        <img
          src="https://img.shields.io/badge/git-%23F05033.svg?style=flat&amp;logo=git&amp;logoColor=white"
          alt="Git"
        ></img>
        <img
          src="https://img.shields.io/badge/node.js-6DA55F?style=flat&amp;logo=node.js&amp;logoColor=white"
          alt="NodeJS"
        ></img>
        <img
          src="https://img.shields.io/badge/nodemon-%23323330.svg?style=flat&amp;logo=nodemon&amp;logoColor=%BBDEAD"
          alt="Nodemon"
        ></img>

        <img
          src="https://img.shields.io/badge/pnpm-%234a4a4a.svg?style=flat&amp;logo=pnpm&amp;logoColor=f69220"
          alt="PNPM"
        ></img>
        <img
          src="https://img.shields.io/badge/React-%2320232a.svg?style=flat&amp;logo=react&amp;logoColor=%2361DAFB"
          alt="React"
        ></img>
        <img
          src="https://img.shields.io/badge/Vite-%23646CFF.svg?style=flat&amp;logo=vite&amp;logoColor=white"
          alt="Vite"
        ></img>
        <img
          src="https://img.shields.io/badge/Tailwind%20CSS-%2338B2AC.svg?style=flat&amp;logo=tailwind-css&amp;logoColor=white"
          alt="TailwindCSS"
        ></img>

        <img
          src="https://img.shields.io/badge/Redis-%23DD0031.svg?style=flat&amp;logo=redis&amp;logoColor=white"
          alt="Redis"
        ></img>
        <img
          src="https://img.shields.io/badge/RabbitMQ-FF6600?style=flat&amp;logo=rabbitmq&amp;logoColor=white"
          alt="RabbitMQ"
        ></img>
        <img
          src="https://img.shields.io/badge/GitHub-%23121011.svg?style=flat&amp;logo=github&amp;logoColor=white"
          alt="GitHub"
        ></img>
        <img
          src="https://img.shields.io/badge/PostgreSQL-%23316192.svg?style=flat&amp;logo=postgresql&amp;logoColor=white"
          alt="Postgres"
        ></img>
        <img
          src="https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=flat&amp;logo=mongodb&amp;logoColor=white"
          alt="MongoDB"
        ></img>

        <img
          src="https://img.shields.io/badge/Microsoft%20SQL%20Server-CC2927?style=flat&amp;logo=microsoft%20sql%20server&amp;logoColor=white"
          alt="MicrosoftSQLServer"
        ></img>

        <img
          src="https://img.shields.io/badge/GitHub%20Actions-%232671E5.svg?style=flat&amp;logo=githubactions&amp;logoColor=white"
          alt="GitHubActions"
        ></img>

        <img
          src="https://img.shields.io/badge/-ElasticSearch-005571?style=flat&amp;logo=elasticsearch"
          alt="ElasticSearch"
        ></img>
        <img
          src="https://img.shields.io/badge/ESLint-4B3263?style=flat&amp;logo=eslint&amp;logoColor=white"
          alt="ESLint"
        ></img>
        <img
          src="https://img.shields.io/badge/Docker-%230db7ed.svg?style=flat&amp;logo=docker&amp;logoColor=white"
          alt="Docker"
        ></img>
        <img
          src="https://img.shields.io/badge/Postman-FF6C37?style=flat&amp;logo=postman&amp;logoColor=white"
          alt="Postman"
        ></img>
        <img
          src="https://img.shields.io/badge/-Swagger-%23Clojure?style=flat&amp;logo=swagger&amp;logoColor=white"
          alt="Swagger"
        ></img>
      </div>
    </div>
  );
}
